name: CIF
on:
  workflow_dispatch:
  pull_request:

jobs:
  build-duckdb:
    name: Build 
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      # BUILD_ICU: 1
      # BUILD_JSON: 1
      # BUILD_TPCH: 1
      # BUILD_TPCDS: 1
      # BUILD_PARQUET: 1
      # BUILD_JEMALLOC: 1
      # CRASH_ON_ASSERT: 1
      GEN: ninja

    steps:
      - name: Dependencies
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build ccache

      - uses: actions/checkout@v4
        with:
          repository: hmeriann/duckdb
          fetch-depth: 0

      - name: create build sqlsmith extension file
        shell: bash
        run: |
          echo "duckdb_extension_load(sqlsmith 
            GIT_URL ${{ github.head_ref }} 
            GIT_TAG ${{ github.ref_name }}
          )" > sqlsmith.cmake

      - name: Build
        shell: bash
        run: |
          echo cat sqlsmith.cmake

      - uses: actions/upload-artifact@v4
        with:
          name: duckdb
          path: build/debug/duckdb
