- name: Fuzz
  shell: bash
  run: |
      chmod +x duckdb
      runtime="10 minute"
      endtime=$(date -ud "$runtime" +%s)
      cd duckdb_sqlsmith
  
      while [[ $(date -u +%s) -le $endtime ]]
      do
          echo "Time Now: `date +%H:%M:%S`"
          python3 scripts/run_fuzzer.py --no_checks --${{ matrix.fuzzer }} --${{ matrix.data }} --max_queries=1000 --shell=../duckdb
      done
